[package]
name = "pathtracer"
version = "0.1.0"
authors = ["Matt Rudder <matt@mattrudder.com>"]

[dependencies]
minifb = "0.10"
rand = "0.5"
rayon = "1.0"
lazy_static = "1.1.0"
threadpool = "1.7.1"
num_cpus = "1.8.0"
